spring:
  application:
    name: product-service

server:
  port: 1002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-5d3g.onrender.com/eureka